### ISSUE TITLE
header file missing???

### ISSUE THREAD

**Issue by yudiannlu** [KjellKod/g3log-rotate-example#1]
In the example, g3log-rotate-example, have a header file <g3log/std2_make_unique.hpp> included?
where is it?

**Comment by KjellKod** [comment]
Hi, 

This repo isn't maintained but feel free to do a pull request to get it working. 
The `std2 make_unique` is no longer needed and the include can be removed and the 
`std2` can be replaced for a `std` in the line
```
worker->addSink(std2::make_unique<LogRotate>(argv[0], path),
```

For more examples please look at the g3log and the g3sinks repos
